version: '3.7'

services:
    mongostandalone:
        image: 'mongo'
        container_name: 'mongostandalone'
        hostname: mongostandalone
        env_file:
            - .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        ports:
            - '27017:27017'
        networks:
            - mongonetwork    
    mongo-express:
        container_name: mongo_express_container
        image: mongo-express
        ports:
            - 8081:8081
        env_file:
            - .env
        environment:
            ME_CONFIG_MONGODB_SERVER: 'mongostandalone'
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        links:
            - mongostandalone
        networks:
            - mongonetwork
        depends_on:
            - mongostandalone
networks:
  mongonetwork: